name: keepbilling
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  charts_flutter: ^0.12.0
  provider: ^6.0.5
  google_fonts: ^3.0.1
  shared_preferences: ^2.0.17
  flutter_pdfview: ^1.2.5
  file_picker: ^5.2.5
  path: ^1.8.1
  path_provider: ^2.0.12
  intl: ^0.17.0
  url_launcher: ^6.1.8

  share_plus: ^6.3.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1


flutter:
  assets:
      - assets/
  
  uses-material-design: true

  